### PR TITLE
EBH-2402

### PR DESCRIPTION
**Pull request by Jay-Miles**
Request for numbers of pre-filtering variants in MYE VCFs which intersect with the capture bed

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10)

### CODE REVIEW

**Review by woook — COMMENTED** [review]
I'm not doing the code review - but I'm not sure it makes sense to include the pindel variants in this (as I don't think that's what Ilenia's after - of course I haven't spoken to her but still...)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-:-Nq-7WcZAIaBOCYEgMBA:b-xlibgn)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @nadia31415)

**Review by nadia31415 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10)* status: all files reviewed, 4 unresolved discussions (waiting on @Jay-Miles)

___
*[`EBH-2402/ebh_2402.sh` line 39 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1iYf866IMs3kokcNO:-Nq1iYf866IMs3kokcNP:b-c6pn9f) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/ebh_2402.sh#L39)):*
> ```Shell
>         echo "Downloading ${name}"
>         dx download "$vcf" -o "$dl_path" -f --no-progress
>     fi
> ```

Might be useful for next time to add a logging message and write out into .txt file any VCFs that weren't successful downloading (more for if you were to download samples that may include archived files)
___
*[`EBH-2402/ebh_2402.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1kdgf7ZVt_BIokZ--:-Nq1kdgf7ZVt_BIokZ-0:bcziwft) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/ebh_2402.sh#L66)):*
> ```Shell
> 
> echo "Intersecting files"
> ```

Might be helpful to add a comment and separate the 2 loops for each file type 
___
*[`EBH-2402/README.md` line 5 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1mvFw5mGGdkpFbzSx:-Nq1mvFw5mGGdkpFbzSy:b15cz7a) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/README.md#L5)):*
> ```Markdown
> Original request: "Ilenia would like to know how many variants are called per case (in general) within the target regions of the MYE assay, prior to any filtering."
> 
> The ebh_2402.sh Bash script takes a DNAnexus project ID as input. It downloads the unfiltered small variant VCFs and indel VCFs from that project, intersects them with the MYE assay bed file, counts the numbers of variants in the output of intersection, and generates descriptive statistics via the ebh_2402.py Python script.
> ```

Nice, this clarifies the purpose of each script clearly.
___
*[`EBH-2402/README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1hBYU0TSNn3lN1Mql:-Nq1hBYU0TSNn3lN1Mqm:brp35d3) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/README.md#L11)):*
> ```Markdown
> The small variant VCFs used are the outputs of Sentieon somatic tnhaplotyper 2 (*_markdup_recalibrated_tnhaplotyper2.vcf.gz).
> 
> The indel VCFs used are the outputs of CgpPindel (*_vs_TA2_S59_L008_tumor.flagged.vcf.gz).
> ```

I think there was a comment on why to use cgppindel VCFs but I understand why this was done, it's to evaluate 2 different circumstances (small variants and INDELs). 
One thing to note about cgppindel is that it is "optimized for detecting somatic insertions" (https://github.com/eastgenomics/eggd_cgppindel). This may/may not mean filtering has done.

**Review by Jay-Miles — COMMENTED** [review]
Checked with Ilenia, she does want indels as well. Will note when I reply to the ticket that cgppindel may include some level of filtering.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-:-Nq2KIKQDx1QF6UyMAqD:byah24k)* status: all files reviewed, 4 unresolved discussions (waiting on @nadia31415)

___
*[`EBH-2402/ebh_2402.sh` line 39 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1iYf866IMs3kokcNO:-Nq2KUtlDfa2tR4v7QfY:b-ky7kwt) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/ebh_2402.sh#L39)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Might be useful for next time to add a logging message and write out into .txt file any VCFs that weren't successful downloading (more for if you were to download samples that may include archived files)
</blockquote></details>

I've modified the code so that it prints a message if a file isn't available.
___
*[`EBH-2402/ebh_2402.sh` line 66 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1kdgf7ZVt_BIokZ--:-Nq2KkXECd52WwvAoiGY:b-5g3114) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/ebh_2402.sh#L66)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Might be helpful to add a comment and separate the 2 loops for each file type
</blockquote></details>

Modified the code so that download and intersection are done in the same loop for each file type, and there are comments separating the two loops.
___
*[`EBH-2402/README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1hBYU0TSNn3lN1Mql:-Nq2KyX4EpSrlAASQTfd:b-bq1d46) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/README.md#L11)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

I think there was a comment on why to use cgppindel VCFs but I understand why this was done, it's to evaluate 2 different circumstances (small variants and INDELs). 
One thing to note about cgppindel is that it is "optimized for detecting somatic insertions" (https://github.com/eastgenomics/eggd_cgppindel). This may/may not mean filtering has done.
</blockquote></details>

Thanks for pointing this out, I didn't know that. I'll mention that when I reply to the ticket.

**Comment by woook** [comment]
Sorry but to be clear about indels:
mutect2 calls indels
cgppindel additionally calls indels in specific genes that tend to have bigger indels
most of the time, the mutect2 indels and the cgppindel indels are the same

So when Ilenia is asking for indels, what does she mean?

**Review by nadia31415 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Jay-Miles)

**Review by Jay-Miles — COMMENTED** [review]
So does the output of Sentieon BAM to VCF also contain indels? If so I'll take CgpPindel out.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-:-Nq2i3kZ6_kv9obBeQVr:bznavv)* status: all files reviewed, 1 unresolved discussion (waiting on @Jay-Miles)

**Review by Jay-Miles — COMMENTED** [review]
That was a silly question, I can just look at an output file and see that it contains indels. I've removed the CgpPindel stuff, I'll clarify in the ticket response that the variants I've counted are those from the Sentieon BAM to VCF output.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-:-Nq2mZbMBNCv8OBpI4Dx:b-go11w6)* status: all files reviewed, 1 unresolved discussion (waiting on @Jay-Miles)

**Review by Jay-Miles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @nadia31415)

___
*[`EBH-2402/README.md` line 5 at r1](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-Nq1mvFw5mGGdkpFbzSx:-Nq2qUilDKY5cOmSFWlX:b-7z474x) ([raw file](https://github.com/eastgenomics/Haemonc_requests/blob/c6c6849369b0eb11025b99730dd478418ffd47ca/EBH-2402/README.md#L5)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Nice, this clarifies the purpose of each script clearly.
</blockquote></details>

Thanks :)

**Review by nadia31415 — APPROVED** [review]
Code follows a clear and logical order, bedtools intersect uses correct bed file for Sentieon VCFs with appropriate stats metrics as output. Also using sentieon VCFs alone makes sense given these include small variants and INDELs without prior filtering 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Haemonc_requests/10#-:-Nq2rTs41aJKrO70uDsw:b2odqi5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jay-Miles)

**Comment by woook** [comment]
Thanks Jay - I think it makes sense to omit cgppindel calls and let them know :+1:

**Pull request merged**
