### PR TITLE
URA 97 Generate bed, exons and probes for HaemOnc transcripts

### PR DESCRIPTION
**Pull request by Aisha-D**
- Script to generate bed and exon file from list of transcripts.
- Files and commands used to generate probes file

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`URA-97/220427_HaemOnc_v2_transcripts.tsv` line 1 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18Gl313UkM287roRi9:-N18Gl313UkM287roRiA:bwmv4b2) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/220427_HaemOnc_v2_transcripts.tsv#L1)):*
> ```TSV
> NM_015338
> ```

could you add another readme inside the `URA-97` dir with just a line explaining what each of this files are / where they've come from / what they're for?
___
*[`URA-97/220427_HaemOnc_v2_transcripts.tsv` line 4 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18H-SS7KHB2m9mmQ-Q:-N18H-SS7KHB2m9mmQ-R:b6k7udu) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/220427_HaemOnc_v2_transcripts.tsv#L4)):*
> ```TSV
> NM_000051
> NM_001123385
> NM_001165
> ```

are you doing some testing in your docs to show these are all correct or do I need to check them all?
___
*[`URA-97/generate_probes.sh` line 1 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18H8i8A2uPB_6fT_Z8:-N18H8i8A2uPB_6fT_Z9:bo9qv6h) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/generate_probes.sh#L1)):*
> ```Shell
> # cut first three columns as the fourth contains genes for some probes
> ```

can you add a bit more to this to explain what the file is for
___
*[`URA-97/Transcript_cellbase_query.py` line 108 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18GS6A301pjt5WYy-n:-N18GS6A301pjt5WYy-o:bnumk5) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/Transcript_cellbase_query.py#L108)):*
> ```Python
>             df = df.append(transcript_table)
> 
>     df[['exon_start']] = df[['exon_start']] - 5
> ```

I assume this is to add flank regions? are we recording somewhere what flank we use? (this is more me asking because i don't know than questioning if its correct)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`URA-97/220427_HaemOnc_v2_transcripts.tsv` line 1 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18Gl313UkM287roRi9:-N18M2PL0O0ib_ZkTnHz:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/220427_HaemOnc_v2_transcripts.tsv#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you add another readme inside the `URA-97` dir with just a line explaining what each of this files are / where they've come from / what they're for?
</blockquote></details>

Done.
___
*[`URA-97/220427_HaemOnc_v2_transcripts.tsv` line 4 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18H-SS7KHB2m9mmQ-Q:-N18M7Sn0e17ShB9ZR83:bmr569f) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/220427_HaemOnc_v2_transcripts.tsv#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are you doing some testing in your docs to show these are all correct or do I need to check them all?
</blockquote></details>

I did some checking by ensuring all regions in the bed file exist in probes file https://cuhbioinformatics.atlassian.net/wiki/spaces/URA/pages/2598928387/coding+unrestricted+GRCh38+myeloid+5bp+flank+v2.0.0.bed . But I am unsure of what other testing is required?
___
*[`URA-97/generate_probes.sh` line 1 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18H8i8A2uPB_6fT_Z8:-N18MH2U6hGYF1jg5gh4:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/generate_probes.sh#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a bit more to this to explain what the file is for
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`URA-97/Transcript_cellbase_query.py` line 108 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6#-N18GS6A301pjt5WYy-n:-N18MZFK5MnYf1E6yM50:b-9td3tr) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/276781467123bf8e912e190dfebccfc66221a747/URA-97/Transcript_cellbase_query.py#L108)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I assume this is to add flank regions? are we recording somewhere what flank we use? (this is more me asking because i don't know than questioning if its correct)
</blockquote></details>

The probes are flanked 5bp  so I think thats why 5bp is selected. For version 1 (existing bed file), the documentation is in GEN.BI.114.  The exons file was generated using this script https://github.com/eastgenomics/nirvana_gff_to_bed/blob/master/gff_to_bed.py Then the required genes/transcripts were selected from the exons file to be used as the bed file.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
