### PR TITLE
HaemOnc bed and exons files for new genes

### PR DESCRIPTION
**Pull request by Aisha-D**
- Generates exons and bed file with 5bp padding
- Examples of output generated https://platform.dnanexus.com/projects/G8GQjJQ4GfF7bX84472YPfk2/data/data_files

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 9 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZsn87-RMATYDmVJz1:-MxZsn87-RMATYDmVJz2:b-uqp6np) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L9)):*
> ```Python
> 
> 
> def query_cellbasedict(exon_dict):
> ```

docstring for function
___
*[EBH-895/exons_temp.py, line 21 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTBFf3alVUkjljkMz:-MxZTBFf3alVUkjljkN-:bs26x68) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L21)):*
> ```Python
> 
> 
> transcript_list = ['NM_014915', 'NM_000633',
> ```

can everything not in a function be under the `if __name__ == "__main_":`block, doesn't need to then call a separate `main()` function but it is just so its tidier and limits global variables
___
*[EBH-895/exons_temp.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTi6B9RGUBvYbHneD:-MxZTi6B9RGUBvYbHneE:b-t58185) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L43)):*
> ```Python
> 
>     if not data['responses'][0]['results']:
>         print("RefSeq transcript does not exist in cellbase")
> ```

do we need to catch / log these?
___
*[EBH-895/exons_temp.py, line 50 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTx82E862CnLCMCpU:-MxZTx82E862CnLCMCpV:btcf8q4) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L50)):*
> ```Python
>         # loop through each exon for a transcript and make a long list of dict
>         list_txs_dict = []
>         for exon in range(exons_num):
> ```

I don't _think_ you need the use of `exons_num` and `range()` here since it is a dict of dicts (at least I think it is), just doing this should work:
```
for exon in data['responses'][0]['results'][0]['exons']:
    exon_dict = data['responses'][0]['results'][0]['exons'][exon]
```

slightly nicer formatting:
```
all_exon_data_dicts = data['responses'][0]['results'][0]['exons'][exon]

for exon in all_exon_data:
    exon_dict = all_exon_data_dicts[exon]
```
___
*[EBH-895/exons_temp.py, line 52 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXXqwD0ETThrZd6za:-MxZXXqwD0ETThrZd6zb:b-numica) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L52)):*
> ```Python
>         for exon in range(exons_num):
>             exon_dict = data['responses'][0]['results'][0]['exons'][exon]
>             # print(exon_dict)
> ```

commented print
___
*[EBH-895/exons_temp.py, line 53 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXa1cE3KulJXZnuEh:-MxZXa1cE3KulJXZnuEi:b-pcsf6v) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L53)):*
> ```Python
>             exon_dict = data['responses'][0]['results'][0]['exons'][exon]
>             # print(exon_dict)
>             if exon_dict["phase"] != -1:
> ```

what is `phase`?
___
*[EBH-895/exons_temp.py, line 57 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXdQQ5CTmnD2DZiSA:-MxZXdQQ5CTmnD2DZiSB:b5pacl) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L57)):*
> ```Python
>                 list_txs_dict.append(extracted_exons_dict)
>             else:
>                 print("exon " + str(exon) + " is a non coding exon")
> ```

using f strings is nicer / faster / more readable (minor thing though):
`f"exon {str(exon)} is a non coding exon"`
___
*[EBH-895/exons_temp.py, line 75 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZsTOF5sXSXXU7SxLo:-MxZsTOF5sXSXXU7SxLp:b-ftnh2) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L75)):*
> ```Python
>         header=False, index=False)
> 
> df.to_csv("exons_nirvana_GRCh38_5bp_flank_v2.0_new_capture_regions_only.tsv", sep="\t",
> ```

why have you got 2 `df.to_csv()` when both look to be the same dataframe with different output names?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[EBH-895/exons_temp.py, line 9 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZsn87-RMATYDmVJz1:-Mx_BKw18JLJ5Eg_oJDI:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L9)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

docstring for function
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 21 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTBFf3alVUkjljkMz:-Mx_BLcg5fhZ_bU2F_IZ:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L21)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can everything not in a function be under the `if __name__ == "__main_":`block, doesn't need to then call a separate `main()` function but it is just so its tidier and limits global variables
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTi6B9RGUBvYbHneD:-Mx_BOeGCowt7YHxdIAh:btu68wa) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L43)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do we need to catch / log these?
</blockquote></details>

Done. Removed it as it's no longer needed.
___
*[EBH-895/exons_temp.py, line 50 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZTx82E862CnLCMCpU:-Mx_BS323rMpltq3Jw4k:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L50)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I don't _think_ you need the use of `exons_num` and `range()` here since it is a dict of dicts (at least I think it is), just doing this should work:
```
for exon in data['responses'][0]['results'][0]['exons']:
    exon_dict = data['responses'][0]['results'][0]['exons'][exon]
```

slightly nicer formatting:
```
all_exon_data_dicts = data['responses'][0]['results'][0]['exons'][exon]

for exon in all_exon_data:
    exon_dict = all_exon_data_dicts[exon]
```
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 52 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXXqwD0ETThrZd6za:-Mx_BS_XBs2P6bqxTRO2:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L52)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

commented print
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 53 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXa1cE3KulJXZnuEh:-Mx_BUJO-Q9lGEo9N60o:bux2lj3) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L53)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is `phase`?
</blockquote></details>

Done. Added in comments what is it.
___
*[EBH-895/exons_temp.py, line 57 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXdQQ5CTmnD2DZiSA:-Mx_BWWnAlezS2W1n_Ad:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L57)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

using f strings is nicer / faster / more readable (minor thing though):
`f"exon {str(exon)} is a non coding exon"`
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 75 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZsTOF5sXSXXU7SxLo:-Mx_BX15E_KhQ2vedF7q:b-xugclx) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L75)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why have you got 2 `df.to_csv()` when both look to be the same dataframe with different output names?
</blockquote></details>

Cause these files are appended to existing files so to not confuse myself I save all three with separate names.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 57 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXdQQ5CTmnD2DZiSA:-Mx_EgvbE42dqN4k6bv1:bkouyk1) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L57)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Done.
</blockquote></details>

f strings use `{   }` in place of `+` for string concatenation, and also allow for function calls in the curly bois too
___
*[EBH-895/exons_temp.py, line 24 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_FdJz6DeWk02Bhu1M:-Mx_FdJz6DeWk02Bhu1N:b-ixnawq) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/fc0a1fde8e8b8fb5dec401d772ee81067aff544b/EBH-895/exons_temp.py#L24)):*
> ```Python
>     txs_dict['chr'] = 'chr' + exon_dict["chromosome"]
>     txs_dict['exon_start'] = exon_dict["genomicCodingStart"]
>     # We need to include the UTR region (negative strand so its the end)
> ```

do we also need the FLT3 intron region?
___
*[EBH-895/exons_temp.py, line 45 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_FE3y-Cs3R7JwxwSQ:-Mx_FE3y-Cs3R7JwxwSR:bn9a2gr) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/fc0a1fde8e8b8fb5dec401d772ee81067aff544b/EBH-895/exons_temp.py#L45)):*
> ```Python
>        files so it's seperate outputs makes it easier for appending files.
>     """
>     transcript_list = ['NM_014915', 'NM_000633',
> ```

should these be an input so that we can use this without changing the code for the next capture change

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[EBH-895/exons_temp.py, line 57 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxZXdQQ5CTmnD2DZiSA:-Mx_LK705uzY5U-MWcjn:bf0px8g) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/3c50960b230d85d243a31d20763072189a20ea5f/EBH-895/exons_temp.py#L57)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

f strings use `{   }` in place of `+` for string concatenation, and also allow for function calls in the curly bois too
</blockquote></details>

My eyes skipped over those +'s XD I have corrected it now.
___
*[EBH-895/exons_temp.py, line 24 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_FdJz6DeWk02Bhu1M:-Mx_Hhwp1OTbH7BV3yGm:b6y4kle) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/fc0a1fde8e8b8fb5dec401d772ee81067aff544b/EBH-895/exons_temp.py#L24)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do we also need the FLT3 intron region?
</blockquote></details>

No, the intron region is used to help detect FLT3 ITDs better. I'll verify this one more time, hang on.
___
*[EBH-895/exons_temp.py, line 45 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_FE3y-Cs3R7JwxwSQ:-Mx_L5BqAuxBgFDG-BaW:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/fc0a1fde8e8b8fb5dec401d772ee81067aff544b/EBH-895/exons_temp.py#L45)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should these be an input so that we can use this without changing the code for the next capture change
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 5 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Puc9-rwcr_96TwDi:-Mx_PucACNqG12xLRsbv:b-cz92jw) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L5)):*
> ```Python
> # out of date
> import argparse
> from ast import arg
> ```

accidental import or you using it?
___
*[EBH-895/exons_temp.py, line 13 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_OUm44bPlAeri8Rjg:-Mx_OUm44bPlAeri8Rjh:b-a27qpg) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L13)):*
> ```Python
>     """Parse through arguements
>     Returns:
>         args: Variable that you can extract relevant
> ```

argument typo, also returns argparse.Namespace object if you were curious what to call it :P 



_Code quote:_
```Python
    """Parse through arguements
    Returns:
        args: Variable that you can extract relevant
        arguements inputs needed
```
___
*[EBH-895/exons_temp.py, line 67 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Ovku8jDc3f4d1tBZ:-Mx_Ovkv3PPx77zpI3F-:b-pvo3ow) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L67)):*
> ```Python
>     """
>     args = parse_args()
>     txs_file = open(args.transcript_file, "r")
> ```

better practice for opening files is to use `with open()` which will automatically close file objects for you:

```
with open (args.transcript_file, "r") as txs_file:
    transcript_list = txs_file.read().splitlines()
    transcript_list = list(filter(None, transcript_list))

```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[EBH-895/exons_temp.py, line 5 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Puc9-rwcr_96TwDi:-Mx_QFSUCVNDI1lRfM11:b4pidnu) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

accidental import or you using it?
</blockquote></details>

accidental import... :eyes: 
___
*[EBH-895/exons_temp.py, line 13 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_OUm44bPlAeri8Rjg:-Mxd8I-8EBrTVUfipXqQ:bt2ybnl) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

argument typo, also returns argparse.Namespace object if you were curious what to call it :P 
</blockquote></details>

call what Namespace, slightly confused
___
*[EBH-895/exons_temp.py, line 67 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Ovku8jDc3f4d1tBZ:-Mxd8MKU9jU5qkKlCKdI:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L67)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

better practice for opening files is to use `with open()` which will automatically close file objects for you:

```
with open (args.transcript_file, "r") as txs_file:
    transcript_list = txs_file.read().splitlines()
    transcript_list = list(filter(None, transcript_list))

```
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 13 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_OUm44bPlAeri8Rjg:-MxdpGhFCu4gr6oWDJuo:bry48yf) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L13)):*
as in in the docstring for what it returns, can be useful to know about namespaces as you can use them to store data in for other things:
```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> args = parser.parse_args()
>>> type(args)
<class 'argparse.Namespace'>
```

This is a nice short post with examples on how else you can use namespaces inplace of dicts / data classes: https://nickp60.github.io/python/blog/2017/12/05/abusing-python-namespaces.html

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 13 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_OUm44bPlAeri8Rjg:-MxdpqY2DQ9jW3baDivL:by3ezkc) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

as in in the docstring for what it returns, can be useful to know about namespaces as you can use them to store data in for other things:
```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> args = parser.parse_args()
>>> type(args)
<class 'argparse.Namespace'>
```

This is a nice short post with examples on how else you can use namespaces inplace of dicts / data classes: https://nickp60.github.io/python/blog/2017/12/05/abusing-python-namespaces.html
</blockquote></details>

nothing really to change here btw, just suggestions

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 67 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Ovku8jDc3f4d1tBZ:-MxdqLhM1zcVIUYj_Z3w:bncjxg) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L67)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm I put a space after the `open` sorry :upside_down_face: 

also can remove the `.close()` after

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[EBH-895/exons_temp.py, line 13 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_OUm44bPlAeri8Rjg:-MxeRSv--UsbTGEOtm3l:bllyuyw) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

nothing really to change here btw, just suggestions
</blockquote></details>

This took a while to grasp that article but got it thanks :) Never knew that type of data existed, registered it as a variable
___
*[EBH-895/exons_temp.py, line 67 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-Mx_Ovku8jDc3f4d1tBZ:-MxeS2bc4LoQztTXL1MQ:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/e292913ba694300bb768e1603e1b73b2d6ee4079/EBH-895/exons_temp.py#L67)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

hmm I put a space after the `open` sorry :upside_down_face: 

also can remove the `.close()` after
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-895/exons_temp.py, line 110 at r10](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxekKPcBKtugvNS_gvO:-MxekKPcBKtugvNS_gvP:b-t4dtws) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/ad62d9799dbb892f57d921f1c2b0b81a2af58427/EBH-895/exons_temp.py#L110)):*
> ```Python
>     txs_dict = {}
>     txs_dict['chr'] = 'chr' + data['responses'][0]['results'][0]['chromosome']
>     # Cellbase laways read from left to right regardless of +ve or
> ```

always



_Code quote:_
```Python
laways
```
___
*[EBH-895/exons_temp.py, line 111 at r10](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxekEp7CojT7oSCtJ87:-MxekEp7CojT7oSCtJ88:b7km96m) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/ad62d9799dbb892f57d921f1c2b0b81a2af58427/EBH-895/exons_temp.py#L111)):*
> ```Python
>     txs_dict['chr'] = 'chr' + data['responses'][0]['results'][0]['chromosome']
>     # Cellbase laways read from left to right regardless of +ve or
>     # -ve strand, so for the intron the start will be end of exon 15
> ```

comment here doesn't match exon numbers below, is one wrong?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[EBH-895/exons_temp.py, line 110 at r10](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxekKPcBKtugvNS_gvO:-MxeqZBo8foEKSlcHvl8:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/ad62d9799dbb892f57d921f1c2b0b81a2af58427/EBH-895/exons_temp.py#L110)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

always
</blockquote></details>

Done.
___
*[EBH-895/exons_temp.py, line 111 at r10](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1#-MxekEp7CojT7oSCtJ87:-MxeqZqY1DbhPWVOjJ4P:bcwcsgz) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/ad62d9799dbb892f57d921f1c2b0b81a2af58427/EBH-895/exons_temp.py#L111)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment here doesn't match exon numbers below, is one wrong?
</blockquote></details>

exon numbering below as in here ```all_exons[14]['end']``` ?  It's querying from a list so offsets it by 1

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
