### PR TITLE
EBH-929 Anonymise samples

### PR DESCRIPTION
**Pull request by Aisha-D**
- Removes the first column of a tsv file and replaces anything before ```markdup_recalibrated``` with a random number
- Log out file contains what each sample name has been replaced with

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-929/anonymise_samples/bin/anonymise_samples.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRPxE8Db3u46RW17CE:-MyRPxE8Db3u46RW17CF:bl297n3) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples.py#L43)):*
> ```Python
>     df = pd.read_csv(file, sep='\t')
> 
>     df2 = df.drop(df.columns[0], axis=1)
> ```

any reason to create a new dataframe instead of assigning back to the current one? For this is it probably doesn't matter, but for big dataframes and doing more at once it will use a lot more memory since it will create a whole new copy in memory, so you should reduce the amount of new ones you create. Also `.drop()` supports `inplace=True` so you don't even have to assign back and can just do `df.drop(df.columns[0], axis=1, inplace=True)`
___
*[EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh, line 2 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRRUNE3RkQll7eqhdH:-MyRRUNFBv0usIwIPoc2:bpv14nc) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh#L2)):*
> ```Shell
> ## Run this script when current location is in the data file
> ```

not sure this needs 2 scripts, could do it all just in python by providing an input dir of files and output dir  as args, then something like:
```
import os
from random import randint

for file in os.listdir(input_dir_of_files):
    num = randint(10000, 99999)  # random 5 digit numbner

    name = f"{num}_markdup_recalibrated_tnhaplotyper2_allgenes.tsv"
    output_file = os.path.join(args.output_path, name)

    ## read in and do what you did above

    
```

or all in bash would be something like:
```
mkdir anonymised

for file in $(find . -type f -name "*.tsv"); do
    random_num=${RANDOM:0:5}
    cut -f 2- $file > "anonymised/${random_num}_markdup_recalibrated_tnhaplotyper2_allgenes.tsv"
done
```

just simpler to keep it all in one language / script

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh, line 2 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRRUNE3RkQll7eqhdH:-MyRVur2ByfE8yE66gIa:b-7atali) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not sure this needs 2 scripts, could do it all just in python by providing an input dir of files and output dir  as args, then something like:
```
import os
from random import randint

for file in os.listdir(input_dir_of_files):
    num = randint(10000, 99999)  # random 5 digit numbner

    name = f"{num}_markdup_recalibrated_tnhaplotyper2_allgenes.tsv"
    output_file = os.path.join(args.output_path, name)

    ## read in and do what you did above

    
```

or all in bash would be something like:
```
mkdir anonymised

for file in $(find . -type f -name "*.tsv"); do
    random_num=${RANDOM:0:5}
    cut -f 2- $file > "anonymised/${random_num}_markdup_recalibrated_tnhaplotyper2_allgenes.tsv"
done
```

just simpler to keep it all in one language / script
</blockquote></details>

omg it can be done in one script !! I created the python initially to handle the xlsx and forgot it wasn't needed for tsv files. Removed the python script and handled it in the bash script now 
___
*[EBH-929/anonymise_samples/bin/anonymise_samples.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRPxE8Db3u46RW17CE:-MyR_H33062Q_3iwnbNW:bu9k7tm) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples.py#L43)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

any reason to create a new dataframe instead of assigning back to the current one? For this is it probably doesn't matter, but for big dataframes and doing more at once it will use a lot more memory since it will create a whole new copy in memory, so you should reduce the amount of new ones you create. Also `.drop()` supports `inplace=True` so you don't even have to assign back and can just do `df.drop(df.columns[0], axis=1, inplace=True)`
</blockquote></details>

Bad habits... during developments I like going back in case whatever amendment was done messes with the recent version.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh, line 17 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRsqFw5BA7KNPTrtmI:-MyRsqFx5SUvNZ3r1AtV:btlveai) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh#L17)):*
> ```Shell
>     do echo ${tmp[$j]};
>     random_num=${RANDOM:0:5};
>     echo S$random_num;
> ```

S? (do you need these echos)?



_Code quote:_
```Shell
S
```
___
*[EBH-929/anonymise_samples/bin/anonymise_samples.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRPxE8Db3u46RW17CE:-MyRsZR83yGkrkQ94_Vm:b-299ra5) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples.py#L43)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Bad habits... during developments I like going back in case whatever amendment was done messes with the recent version. 
</blockquote></details>

that's fair, I do it a lot until I get dataframes with hundreds of thousands of rows and then wonder why my laptop is taking off...

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh, line 17 at r2](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-MyRsqFw5BA7KNPTrtmI:-MyRtJVN7z7zmX1CYgoj:b1l3gfr) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/6d41db5fd4628800a52a31b69196affb79795ff9/EBH-929/anonymise_samples/bin/anonymise_samples_wrapper.sh#L17)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

S? (do you need these echos)?
</blockquote></details>

S is sample - Didn't like seeing numbers alone and so I know its an anonymised sample. Yes the echos are in the logout.txt so in case they ever ask what sample is we can trace back.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/2#-:-MyS-NBG-xSiAwmPCVM7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
