### PR TITLE
URA 72 transcript checks

### PR DESCRIPTION
**Pull request by Aisha-D**
Checks number of COSMIC annotations present per transcript for a gene from the haematopoietic and lymphoid tissue dataset.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)

### CODE REVIEW

**Review by nadia31415 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: all files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @spaul91)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 18 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N187ULi28oCSjF5zU0i:-N187ULi28oCSjF5zU0j:bk34sgg) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L18)):*
> ```
> From COSMIC, the file from "COSMIC Mutation Data" (https://cancer.sanger.ac.uk/cosmic/download) was filtered for cancer "haematopoietic_and_lymphoid_tissue" and downloaded. 
> 
> The aim of this analysis is to see whether the mane transcripts retain more of the variants in cosmic than the altervatives transcripts of a gene. There are a number of ways to track a COSMIC variants, either genomic position, Genomic mutation identifier (COSV) or Legacy mutation identifier (COSM).
> ```

formatting - "There are a number of ways to track a COSMIC variants"
(delete 'a')
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 19 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1868RhAm12oV-LSJh3:-N1868RhAm12oV-LSJh4:b9faejf) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L19)):*
> ```
> 
> The aim of this analysis is to see whether the mane transcripts retain more of the variants in cosmic than the altervatives transcripts of a gene. There are a number of ways to track a COSMIC variants, either genomic position, Genomic mutation identifier (COSV) or Legacy mutation identifier (COSM).
> For this analysis, the Genomic mutation identifier (COSV) will filtered for anything not null then the Legacy mutation identifier (COSM) will be filtered for coding ID (there are COSN which is non coding). Thencosmic variants with no protein mutation description are removed as some COSM are outside exons but labelled COSM as they are thought to impact other transcript functions such as splicing, promoter regions etc.
> ```

formatting - "Thencosmic variants with no protein mutation"
(missed space)
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 192 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N18OutO6DNQptbzoqcn:-N18OutO6DNQptbzoqco:blv053n) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L192)):*
> ```
>   print("-----------------------------")
> }
> ```

Recommendation - for loop repeated 4 times (new genes, old genes etc...)
(could be a function?)



_Code snippet:_
```
  for (i in 1:length(txs)){
    transcripts = txs[i]
    
    print(paste(transcripts, length(unique(df[which(df$ACCESSION_NUMBER %in% transcripts & df$GENOMIC_MUTATION_ID != "null" &  df$MUTATION_DESCRIPTION != "Unknown"), "LEGACY_MUTATION_ID"]))), sep = "_")
    
    row <- c(gene, transcripts, length(unique(df[which(df$ACCESSION_NUMBER %in% transcripts & df$GENOMIC_MUTATION_ID != "null" &  df$MUTATION_DESCRIPTION != "Unknown"), "LEGACY_MUTATION_ID"])))
    summary_tbl <- rbind(summary_tbl, row)
  }
```

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 59 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1D6EEn2bYE-9pz1YWq:-N1D6EEn2bYE-9pz1YWr:b-q05pyr) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L59)):*
> ```
>   # sometimes there are null COSVs which have COSM values but these dont have clear AA annotation
>   # so these can be removed
>   total_COSMs <- unique(df[which(df$GENOMIC_MUTATION_ID != "null" &  df$MUTATION_DESCRIPTION != "Unknown"), "LEGACY_MUTATION_ID"])
> ```

About the input: will it always have "null" for missing IDs (and similarly for mutation description and "Unknown")? Can there ever be empty whitespace "", or plain NA values?

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 12 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1DHgZ86XuWxZu3eLjp:-N1DHgZ86XuWxZu3eLjq:b-2mrwcs) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L12)):*
> ```
> ```{r}
> library(tidyr)
> library("stringr")        
> ```

Super pedantic comment: would recommend either removing the double quotes around this, or adding double quotes to `library(tidyr)` for consistency

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 56 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1DHvY2AzJOA_dX4Vam:-N1DHvY2AzJOA_dX4Van:bvjaheb) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L56)):*
> ```
>   print(paste("The Ensemble transcripts for", gene, " is:", paste(unique(df$ACCESSION_NUMBER), collapse =  " & "), collapse = ""))
> 
>   txs = paste(unique(df$ACCESSION_NUMBER))
> ```

More of me being pedantic! Would recommend using `<-` instead of `=` for alignment with the rest of the script

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 192 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N18OutO6DNQptbzoqcn:-N1DISUE4dQ_eWHvZZqt:brfv82) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L192)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Recommendation - for loop repeated 4 times (new genes, old genes etc...)
(could be a function?)
</blockquote></details>

Agreed with @nadia31415 , and to piggyback off this it may be worth keeping a separate config file with gene names (and if relevant, category a la MANE, not MANE etc.) for the script to read in, instead of hard-coding the gene names into the code

**Comment by spaul91** [comment]
One general bit of feedback that applies to the overall script: I'd recommend making it a plain `.R` script instead of an .Rmd document, and adding the #Introduction section to a README.md file. This'd make it easier to manage dependencies, since we don't have to worry about knitr package updates or anything like that. It looks like the script logs straight to the terminal, so the readout could be covered by the basic .R format

**Review by Aisha-D — COMMENTED** [review]
This was initially an Rmarkdown as I was hoping to control the code and the output during development by producing a HTML each time but since this is final, I can turn it into a R script and input the list of gene inputs on the command line 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-:-N1sVGa296UIwsIUnrMQ:b6hrn3d)* status: all files reviewed, 6 unresolved discussions (waiting on @nadia31415 and @spaul91)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 12 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1DHgZ86XuWxZu3eLjp:-N1sQy480tck5ujgbq_M:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L12)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Super pedantic comment: would recommend either removing the double quotes around this, or adding double quotes to `library(tidyr)` for consistency
</blockquote></details>

Done.
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 18 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N187ULi28oCSjF5zU0i:-N1sR6-d2Xf5tjKrY2Ts:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L18)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

formatting - "There are a number of ways to track a COSMIC variants"
(delete 'a')
</blockquote></details>

Done.
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 19 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1868RhAm12oV-LSJh3:-N1sR6Fc9Wxj1J8qhC_D:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L19)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

formatting - "Thencosmic variants with no protein mutation"
(missed space)
</blockquote></details>

Done.
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 56 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1DHvY2AzJOA_dX4Vam:-N1sRGO52a0kW2UAKhE9:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

More of me being pedantic! Would recommend using `<-` instead of `=` for alignment with the rest of the script
</blockquote></details>

Done.
___
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 59 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1D6EEn2bYE-9pz1YWq:-N1sUMfG9FI0S8F_SZjf:b-54rvjw) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L59)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

About the input: will it always have "null" for missing IDs (and similarly for mutation description and "Unknown")? Can there ever be empty whitespace "", or plain NA values? 
</blockquote></details>

Well, I checked each time manually (another bad practise :( )for each gene and there were no empty cell or plain NA values, here's a check I did for the whole dataframe



_Code snippet:_
```
unique(dat[which(dat$GENOMIC_MUTATION_ID == " " | dat$GENOMIC_MUTATION_ID == "NA" | dat$GENOMIC_MUTATION_ID == "null"), "GENOMIC_MUTATION_ID"])
[1] "null"
unique(dat[which(dat$MUTATION_DESCRIPTION == " " | dat$MUTATION_DESCRIPTION == "NA" | dat$MUTATION_DESCRIPTION == "Unknown"), "MUTATION_DESCRIPTION"])
[1] "Unknown"
```

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.Rmd` line 59 at r3](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N1D6EEn2bYE-9pz1YWq:-N2HivNP1CEnnoPIL5UG:b-ebbg70) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/64d4f2faea315563eb6d2d52fa701cf8a63f8f95/URA-72/COSMIC_HaemOnc_new_genes.Rmd#L59)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Well, I checked each time manually (another bad practise :( )for each gene and there were no empty cell or plain NA values, here's a check I did for the whole dataframe
</blockquote></details>

Cool, thanks :)

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 40 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2HniB03f-irJBXRsO-:-N2HniB03f-irJBXRsO0:b-c6yqx2) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L40)):*
> ```
>   # Calculate unique legacy_mutation_IDs (COSMs) per transcripts
>   group_by(ACCESSION_NUMBER) %>%
>   summarise(n_COSMs = n_distinct(LEGACY_MUTATION_ID), across()) %>%
> ```

why is the `across` function here and empty?

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 11 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2Hnrxw-yjXTA8ihWMo:-N2Hnrxw-yjXTA8ihWMp:b35mwgw) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L11)):*
> ```
>   make_option(c("-c", "--cosmic_data"), action="store", default=NA,type='character',
>               help="COSMIC Mutation Data"),
>   make_option(c("-i", "--input_gene"), action="store", default=NA,type='character',
> ```

would probably call this `input_genes`, or `gene_config` so the user is aware that multiple genes can be submitted at once

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @nadia31415 and @spaul91)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 40 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2HniB03f-irJBXRsO-:-N2HsH9D-k8L46KfY8rR:bsu5vjh) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L40)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

why is the `across` function here and empty?
</blockquote></details>

if summarise is done just on the legacy_mutation_id column then thats the only column retained so across keeps all the columns.

**Review by nadia31415 — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @nadia31415 and @spaul91)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 11 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2Hnrxw-yjXTA8ihWMo:-N2HqvBIEbwaiigVg_Xr:b-vl0uur) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L11)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

would probably call this `input_genes`, or `gene_config` so the user is aware that multiple genes can be submitted at once
</blockquote></details>

agree with sophie, maybe call input_genes for the multiple genes to be submitted

**Review by nadia31415 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: all files reviewed, 3 unresolved discussions (waiting on @spaul91)

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 40 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2HniB03f-irJBXRsO-:-N2LuNFG9DTzIa_DyfwD:brfoe9p) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L40)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

if summarise is done just on the legacy_mutation_id column then thats the only column retained so across keeps all the columns.
</blockquote></details>

Fair enough. This is totally a personal preference, but I'd have used `mutate()` in place of `summarise()` for this purpose, as it does the same thing as `summarise(<funcs>, across())` but makes the dev's intent a bit clearer. In favour of keeping it as is if you prefer!

**Comment by spaul91** [comment]
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 40 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2HniB03f-irJBXRsO-:-N2Lvhwj5HUdNNLuNUuk:bve6u6g) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L40)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Fair enough. This is totally a personal preference, but I'd have used `mutate()` in place of `summarise()` for this purpose, as it does the same thing as `summarise(<funcs>, across())` but makes the dev's intent a bit clearer. In favour of keeping it as is if you prefer!
</blockquote></details>

i.e.: `group_by(ACCESSION_NUMBER) %>% mutate(n_COSMs = n_distinct(LEGACY_MUTATION_ID)) %>% select(<things>) %>% unique()`

**Comment by spaul91** [comment]
:lgtm:

**Review by spaul91 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 41 at r6](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2M3KmXEQN9wjIaijwQ:-N2M3KmXEQN9wjIaijwR:b-55gpuk) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/11f7891c3f87b13c546a6c36cdc8567646085823/URA-72/COSMIC_HaemOnc_new_genes.R#L41)):*
> ```
>   group_by(ACCESSION_NUMBER) %>%
>   summarise(n_COSMs = n_distinct(LEGACY_MUTATION_ID), across()) %>%
>   # order columns
> ```

Can we use HGNC ID's rather than gene symbols as input to avoid gene symbols changing and causing problems



_Code quote:_
```
# order columns
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @nadia31415, @spaul91, and @woook)

___
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 40 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2HniB03f-irJBXRsO-:-N2Lwur2DSwIG2pFUCJF:bjrywi8) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/662707602f80395567e834335b685b35529f10b9/URA-72/COSMIC_HaemOnc_new_genes.R#L40)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

i.e.: `group_by(ACCESSION_NUMBER) %>% mutate(n_COSMs = n_distinct(LEGACY_MUTATION_ID)) %>% select(<things>) %>% unique()`
</blockquote></details>

thats so true, guess my tidyverse studying sold me to use summarise :D 
___
*[`URA-72/COSMIC_HaemOnc_new_genes.R` line 41 at r6](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-N2M3KmXEQN9wjIaijwQ:-N2MHr484bN_VJbIEV3m:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/11f7891c3f87b13c546a6c36cdc8567646085823/URA-72/COSMIC_HaemOnc_new_genes.R#L41)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Can we use HGNC ID's rather than gene symbols as input to avoid gene symbols changing and causing problems
</blockquote></details>

Done.

**Review by woook — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

**Review by woook — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5#-:-N2MPN422y-Ut149K4b-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

**Review by woook — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
