### PR TITLE
EBH 825 

### PR DESCRIPTION
**Pull request by Aisha-D**
- VAF distribution plots
- Merge tsvs into a super tsv :superhero:

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[EBH-825/all_variants_tsv/get_samples.sh, line 4 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7gktB90SW7m7dzQgS:-N-7gktB90SW7m7dzQgT:bep32ql) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/all_variants_tsv/get_samples.sh#L4)):*
> ```Shell
> projects=$(dx find projects --name "002_*MYE")
> 
> for project in $projects;  do      echo $project; file_id=$(dx find data --json --path="$project" --name="*_allgenes.tsv" | jq -r '.[].id');  for file in $file_id; do         dx download $file --no-progress; done; done
> ```

could this be formatted nicer, something like:

```
for project in $projects; do
    echo $project
    file_ids=$(dx find data --json --path="$project" --name="*_allgenes.tsv" | jq -r '.[].id')
    for file in $file_ids; do
         dx download $file --no-progress
    done
done
```
___
*[EBH-825/all_variants_tsv/get_samples.sh, line 7 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7hJ021rLNMFoHXz-Z:-N-7hJ021rLNMFoHXz-_:bj21pu4) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/all_variants_tsv/get_samples.sh#L7)):*
> ```Shell
> 
> 
> # ! The last column is wrapped so for everyline there is extra 5 rows, so to know wc -l 
> ```

I'm confused by this, how do you mean it is wrapped and what is `count` needed for?
___
*[EBH-825/artefacts_vaf_distribution/merge_vcfs.py, line 16 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7hkja1zDeVYdv1pSk:-N-7hkja1zDeVYdv1pSl:b9ki77g) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L16)):*
> ```Python
> for sample_vcf in all_vcfs:
>   # read in sample
>   vcf_df_all = pd.read_csv(sample_vcf, sep="\t",
> ```

does this not read all of the header into the dataframe? `comment='#'` will stop this

if you then need to get the header I'd do something like this: https://github.com/eastgenomics/eggd_generate_workbook/blob/8903637a5daf873d5f4340d3c580d179f74e1da5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L306
___
*[EBH-825/artefacts_vaf_distribution/merge_vcfs.py, line 30 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7iH-R8VM-WxmAW3z6:-N-7iH-R8VM-WxmAW3z7:bsdnitl) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L30)):*
why do you need to iterate over all the rows of the dataframe, are you just building a dictionary of dictionaries, with one dict per row of column values?

if so, you can just directly do it with something like this on a subset of columns:

```
>>> df = pd.DataFrame([{'a':1, 'b':2, 'c':4}, {'a':3, 'b':5, 'c':6}])
>>> df
   a  b  c
0  1  2  4
1  3  5  6

>>> df[['a', 'b']].to_dict('index')
{0: {'a': 1, 'b': 2}, 1: {'a': 3, 'b': 5}}
```
this will be mucchh faster than iterating and is simpler if its what you want :) 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html
___
*[EBH-825/artefacts_vaf_distribution/merge_vcfs.py, line 53 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7js0XBSV6v4GYnq4f:-N-7js0YBnKfBQrQZ0LJ:b-dijz98) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L53)):*
> ```Python
> df['prev_count'] = df['prev_count'].fillna(0).astype(int)
> 
> filtered_df = df[df.prev_count > 20]
> ```

why 20?
___
*[EBH-825/artefacts_vaf_distribution/merge_vcfs.py, line 54 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7k7Y42_slIqb5UaPY:-N-7k7Y42_slIqb5UaPZ:bcfcubc) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L54)):*
> ```Python
> 
> filtered_df = df[df.prev_count > 20]
> df.to_csv("/home/aisha/Documents/Projects/myeloid/haemonc_smalltasks/results/EBH-825/220201_allvcf_merged.tsv", sep="\t", header=True, index=False)
> ```

can you remove paths so we don't have to modify to run it again, if you just want to output where the script is you can access this dir using

```
os.path.realpath(__file__)
```

then for the file as
```
os.path.join(os.path.realpath(__file__), '220201_allvcf_merged.tsv')
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`EBH-825/all_variants_tsv/get_samples.sh` line 4 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7gktB90SW7m7dzQgS:-N1Da52i1G4HPnvhWfM7:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/all_variants_tsv/get_samples.sh#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could this be formatted nicer, something like:

```
for project in $projects; do
    echo $project
    file_ids=$(dx find data --json --path="$project" --name="*_allgenes.tsv" | jq -r '.[].id')
    for file in $file_ids; do
         dx download $file --no-progress
    done
done
```
</blockquote></details>

Done.
___
*[`EBH-825/all_variants_tsv/get_samples.sh` line 7 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7hJ021rLNMFoHXz-Z:-N1Da5XFCK0dDCvoBMw1:blfu5co) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/all_variants_tsv/get_samples.sh#L7)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'm confused by this, how do you mean it is wrapped and what is `count` needed for?
</blockquote></details>

added better comments but used counts to check the correct lines are being added cause idk how to count all lines of all files in go so made this count variable that will store the lines and count them along as I concat the files.
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 16 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7hkja1zDeVYdv1pSk:-N1DfyVC2JlPrYMZ-4xo:bbda4t5) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L16)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this not read all of the header into the dataframe? `comment='#'` will stop this

if you then need to get the header I'd do something like this: https://github.com/eastgenomics/eggd_generate_workbook/blob/8903637a5daf873d5f4340d3c580d179f74e1da5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L306

</blockquote></details>

Done. (I was being lazy about reading stuff in multiple times)
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 53 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7js0XBSV6v4GYnq4f:-N1Dg3Gc1yyrig5A6j_p:bri07uc) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L53)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why 20?
</blockquote></details>

roughly 10% of number of samples in MAF (250)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`EBH-825/all_variants_tsv/get_samples.sh` line 7 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7hJ021rLNMFoHXz-Z:-N1Dl6bvClG_86OsqaXS:b-3oxrs) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/all_variants_tsv/get_samples.sh#L7)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

added better comments but used counts to check the correct lines are being added cause idk how to count all lines of all files in go so made this count variable that will store the lines and count them along as I concat the files.
</blockquote></details>

`sed 1d` will get all lines except the first, so something like `sed 1d ./*.tsv | wc -l` would count all lines in all files matching a given pattern, but what you've done is fine because of the stupid line wrapping on the last column
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 20 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N1Dngai9vEXagz68w3p:-N1Dngai9vEXagz68w3q:byb485r) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/c7827e0490e2d59233dae088178a5ea8eca858b5/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L20)):*
> ```Python
>                     names=cols, compression='infer', comment = "#")
>   # Select rows where it starts with chr (removes the headers)
>   fh = gzip.open(sample_vcf)
> ```

here it is better practice to use `with` as it will close the file for you on finishing and not need to call `fh.close()`:

```
with gzip.open(sample_vcf) as fh:
    # do some things


# no fh.close() needed down here
```
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 22 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N1DnfHW7OwrP3f-U2-H:-N1DnfHW7OwrP3f-U2-I:bscgr6) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/c7827e0490e2d59233dae088178a5ea8eca858b5/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L22)):*
> ```Python
>   fh = gzip.open(sample_vcf)
>   header = []
>   print("Yay")
> ```

print needed?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 30 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7iH-R8VM-WxmAW3z6:-N1Dk2No7_nPwaB6vUv7:bh4lvc5) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L30)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why do you need to iterate over all the rows of the dataframe, are you just building a dictionary of dictionaries, with one dict per row of column values?

if so, you can just directly do it with something like this on a subset of columns:

```
>>> df = pd.DataFrame([{'a':1, 'b':2, 'c':4}, {'a':3, 'b':5, 'c':6}])
>>> df
   a  b  c
0  1  2  4
1  3  5  6

>>> df[['a', 'b']].to_dict('index')
{0: {'a': 1, 'b': 2}, 1: {'a': 3, 'b': 5}}
```
this will be mucchh faster than iterating and is simpler if its what you want :) 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html
</blockquote></details>

Some columns I am splittings from a row so I'm not sure how this method would handle that
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 54 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7k7Y42_slIqb5UaPY:-N1Dk-Uo6RmrL06aWx_r:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L54)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you remove paths so we don't have to modify to run it again, if you just want to output where the script is you can access this dir using

```
os.path.realpath(__file__)
```

then for the file as
```
os.path.join(os.path.realpath(__file__), '220201_allvcf_merged.tsv')
```
</blockquote></details>

Done.
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 20 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N1Dngai9vEXagz68w3p:-N1Ds4uq72bLLfbgv9_a:brhkid8) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/c7827e0490e2d59233dae088178a5ea8eca858b5/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L20)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

here it is better practice to use `with` as it will close the file for you on finishing and not need to call `fh.close()`:

```
with gzip.open(sample_vcf) as fh:
    # do some things


# no fh.close() needed down here
```
</blockquote></details>

oh no close with open?? cool, done it :) 
___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 22 at r7](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N1DnfHW7OwrP3f-U2-H:-N1Ds4oU6BsTTaDGBP8L:b-896fix) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/c7827e0490e2d59233dae088178a5ea8eca858b5/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L22)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

print needed?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`EBH-825/artefacts_vaf_distribution/merge_vcfs.py` line 30 at r5](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-N-7iH-R8VM-WxmAW3z6:-N1E22Rm3YkCB8tuLXVP:bfy28fr) ([raw file](https://github.com/eastgenomics/haemonc_requests/blob/949afca022046c1333bab5ac74ba15ca3ebd8c32/EBH-825/artefacts_vaf_distribution/merge_vcfs.py#L30)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Some columns I am splittings from a row so I'm not sure how this method would handle that
</blockquote></details>

hmmm true, iterating is fine then since you change all the names too, if you did want to modify the values after you could do a dictionary comprehension but its fine as is

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4#-:-N1E2q259Ye5v0EBnvlK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/haemonc_requests/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
